(cl:in-package balboa_core-msg)
(cl:export '(HEADER-VAL
          HEADER
          ARDUINOMILLIS-VAL
          ARDUINOMILLIS
          BATTERYMILLIVOLTS-VAL
          BATTERYMILLIVOLTS
          ANGLEY-VAL
          ANGLEY
          ANGLEX-VAL
          ANGLEX
          ANGLEZ-VAL
          ANGLEZ
          DRIVELEFT-VAL
          DRIVELEFT
          DRIVERIGHT-VAL
          DRIVERIGHT
          SPEEDLEFT-VAL
          SPEEDLEFT
          SPEEDRIGHT-VAL
          SPEEDRIGHT
          DISTANCELEFT-VAL
          DISTANCELEFT
          DISTANCERIGHT-VAL
          DISTANCERIGHT
          SENSORVALUE1-VAL
          SENSORVALUE1
          SENSORVALUE2-VAL
          SENSORVALUE2
          SENSORVALUE3-VAL
          SENSORVALUE3
          SENSORVALUE4-VAL
          SENSORVALUE4
          SENSORVALUE5-VAL
          SENSORVALUE5
          IR-VAL
          IR
))